module.exports.descriptors = [
    'National',
    'Royal',
    'Jazz',
    'New',
    'American',
    'Russian',
    'Modern',
    'Classical',
    'Ritmic',
    'Offical',
    'English',
    'Dutch',
    'First',
    'Best',
    'New',
    'Smooth',
    'French',
    'Diamond'
]

module.exports.places = [
    'Dance',
    'Ballet',
    'Group',
    'Ballet',
    'Dance',
    'Ballet',
    'Ballet',
    'Dance Group',
    'Dance Theatre',
    'Dance Company',
    'Ballet Academy',
    'United Dance Group',
    'Ballet Union',
    'Jazz Dance',
    'Street Dance',
    'Break Dance',
    'Jazz Ballet',
    'Ritmic Dance',
    'Dance Association',
    'Girls',
    'Company'
]
